package technitium

/*
Copyright 2024 The external-dns-technitium-webhook Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strconv"
	"sync"
	"time"

	"github.com/Bugs5382/external-dns-technitium-webhook/internal/metrics"
	"github.com/prometheus/client_golang/prometheus"
	log "github.com/sirupsen/logrus"
)

// APIResponse represents the standard JSON envelope Technitium uses.
type APIResponse struct {
	Status       string          `json:"status"`
	ErrorMessage string          `json:"errorMessage,omitempty"`
	Token        string          `json:"token,omitempty"`
	Response     json.RawMessage `json:"response,omitempty"`
}

// Client represents the Technitium DNS API client.
type Client struct {
	BaseURL    string
	Port       string
	Username   string // Optional if using a static token
	Password   string // Optional if using a static token
	HTTPClient *http.Client

	// Session management
	token         string
	tokenExpiry   time.Time
	isStaticToken bool       // Skips auto-login and session rolling if a user provided a token directly
	mu            sync.Mutex // Protects token state during concurrent calls
}

// NewClientWithCredentials initializes a Technitium API client with credentials and SSL settings.
func NewClientWithCredentials(baseURL string, port int, username, password string, sslVerify bool) *Client {
	return &Client{
		BaseURL:    baseURL,
		Port:       strconv.Itoa(port),
		Username:   username,
		Password:   password,
		HTTPClient: createHTTPClient(sslVerify),
	}
}

// NewClientWithToken initializes a Technitium API client with a static token and SSL settings.
func NewClientWithToken(baseURL string, port int, token string, sslVerify bool) *Client {
	return &Client{
		BaseURL:       baseURL,
		Port:          strconv.Itoa(port),
		token:         token,
		isStaticToken: true,
		HTTPClient:    createHTTPClient(sslVerify),
	}
}

// Helper function to create the HTTP client with optional SSL verification
func createHTTPClient(sslVerify bool) *http.Client {
	tr := &http.Transport{
		TLSClientConfig: &tls.Config{
			InsecureSkipVerify: !sslVerify, // If sslVerify is false, InsecureSkipVerify is true
		},
	}
	return &http.Client{
		Timeout:   10 * time.Second,
		Transport: tr,
	}
}

// Login manually authenticates with the API and stores the session token.
// You usually don't need to call this manually if using credentials, as DoRequest handles it automatically.
func (c *Client) Login() error {
	c.mu.Lock()
	defer c.mu.Unlock()

	return c.loginLocked()
}

// loginLocked handles the login logic without acquiring the lock.
func (c *Client) loginLocked() error {
	if c.isStaticToken {
		return fmt.Errorf("login disabled: client is configured with a static API token")
	}

	metrics.TotalApiCalls.Inc()
	timer := prometheus.NewTimer(metrics.ApiCallLatency.WithLabelValues("login"))
	defer timer.ObserveDuration()

	endpoint := fmt.Sprintf("%s:%s%s", c.BaseURL, c.Port, "/api/user/login")
	req, err := http.NewRequest(http.MethodGet, endpoint, nil)
	if err != nil {
		metrics.FailedApiCallsTotal.Inc()
		return fmt.Errorf("failed to create login request: %w", err)
	}

	// Technitium uses URL query parameters for almost all data inputs
	q := req.URL.Query()
	q.Add("user", c.Username)
	q.Add("pass", c.Password)
	req.URL.RawQuery = q.Encode()

	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		metrics.FailedApiCallsTotal.Inc()
		return fmt.Errorf("login request failed: %w", err)
	}
	defer func() {
		closeErr := resp.Body.Close()
		if closeErr != nil {
			metrics.FailedApiCallsTotal.Inc()
			log.Errorf("Failed to close response body: %v", closeErr)
		}
	}()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		metrics.FailedApiCallsTotal.Inc()
		return fmt.Errorf("failed to read login response: %w", err)
	}

	if resp.StatusCode != http.StatusOK {
		metrics.FailedApiCallsTotal.Inc()
		return fmt.Errorf("unexpected HTTP status %d: %s", resp.StatusCode, string(body))
	}

	var apiResp APIResponse
	if err := json.Unmarshal(body, &apiResp); err != nil {
		metrics.FailedApiCallsTotal.Inc()
		return fmt.Errorf("failed to parse login JSON: %w", err)
	}

	if apiResp.Status != "ok" {
		metrics.FailedApiCallsTotal.Inc()
		return fmt.Errorf("login failed: %s", apiResp.ErrorMessage)
	}

	if apiResp.Token == "" {
		metrics.FailedApiCallsTotal.Inc()
		return fmt.Errorf("login succeeded but no token was returned by the server")
	}

	// Save token and set expiration based on current time + safe buffer
	c.token = apiResp.Token
	c.tokenExpiry = time.Now().Add(sessionBuffer())

	return nil
}

// DoRequest is the central method for interacting with the API.
// It automatically handles injecting the token, tracking session lengths, and re-authenticating (if applicable).
func (c *Client) DoRequest(method, path string, params url.Values) ([]byte, error) {
	startTime := time.Now()

	timer := prometheus.NewTimer(metrics.ApiCallLatency.WithLabelValues(path))
	duration := time.Since(startTime)
	defer timer.ObserveDuration()

	c.mu.Lock()

	if !c.isStaticToken && (c.token == "" || time.Now().After(c.tokenExpiry)) {
		if err := c.loginLocked(); err != nil {
			c.mu.Unlock()
			return nil, fmt.Errorf("auto-login failed: %w", err)
		}
	}

	// Copy token so we can release the lock before making the slow network call
	currentToken := c.token
	c.mu.Unlock()

	if params == nil {
		params = url.Values{}
	}

	params.Set("token", currentToken)

	endpoint := fmt.Sprintf("%s:%s%s", c.BaseURL, c.Port, path)
	req, err := http.NewRequest(method, endpoint, nil)
	if err != nil {
		metrics.FailedApiCallsTotal.Inc()
		return nil, fmt.Errorf("failed to create API request: %w", err)
	}

	req.URL.RawQuery = params.Encode()

	resp, err := c.HTTPClient.Do(req)
	if err != nil {
		metrics.FailedApiCallsTotal.Inc()
		return nil, fmt.Errorf("API request failed: %w", err)
	}
	defer func() {
		closeErr := resp.Body.Close()
		if closeErr != nil {
			metrics.FailedApiCallsTotal.Inc()
			log.Errorf("Failed to close response body: %v", closeErr)
		}
	}()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		metrics.FailedApiCallsTotal.Inc()
		return nil, fmt.Errorf("failed to read API response body: %w", err)
	}

	switch resp.StatusCode {
	case http.StatusOK:
		metrics.TotalApiCalls.Inc()
		metrics.ApiCallLatency.WithLabelValues(path).Observe(duration.Seconds())
		// A successful call resets the Technitium rolling session timer (if applicable)
		if !c.isStaticToken {
			c.mu.Lock()
			c.tokenExpiry = time.Now().Add(sessionBuffer())
			c.mu.Unlock()
		}

	case http.StatusUnauthorized, http.StatusForbidden:
		metrics.FailedApiCallsTotal.Inc()
		metrics.ApiCallLatency.WithLabelValues(path).Observe(duration.Seconds())
		// If the server rejects the token, and it's a managed session, wipe it.
		// The next call will force a fresh login. If it's static, leave it alone but return the error.
		if !c.isStaticToken {
			c.mu.Lock()
			c.token = ""
			c.tokenExpiry = time.Time{}
			c.mu.Unlock()
		}
		return nil, fmt.Errorf("authentication rejected (status %d): %s", resp.StatusCode, string(body))

	default:
		metrics.FailedApiCallsTotal.Inc()
		metrics.ApiCallLatency.WithLabelValues(path).Observe(duration.Seconds())
		// It's good practice to handle other non-200 codes (404, 500, etc.) here
		return nil, fmt.Errorf("unexpected status code %d: %s", resp.StatusCode, string(body))
	}

	return body, nil
}
