package technitium

/*
Copyright 2024 The external-dns-technitium-webhook Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	log "github.com/sirupsen/logrus"
	"sigs.k8s.io/external-dns/endpoint"
	"sigs.k8s.io/external-dns/plan"
	"sigs.k8s.io/external-dns/provider"
)

type Provider struct {
	provider.BaseProvider
	client       *Client
	domainFilter *endpoint.DomainFilter
	config       *StartupConfig
}

// StartupConfig clarifies the method signature
type StartupConfig struct {
	Host       string `env:"TECHNITIUM_HOST,required" envDefault:"localhost"`
	Port       int    `env:"TECHNITIUM_PORT,required" envDefault:"5380"`
	Username   string `env:"TECHNITIUM_USER"`
	Password   string `env:"TECHNITIUM_PASSWORD"`
	Token      string `env:"TECHNITIUM_TOKEN"`
	SessionTTL int    `env:"TECHNITIUM_SESSION_TTL" envDefault:"30"`
	SSLVerify  bool   `env:"TECHNITIUM_SSL_VERIFY" envDefault:"false"`
	DryRun     bool   `env:"TECHNITIUM_DRY_RUN" envDefault:"false"`
	CreatePTR  bool   `env:"TECHNITIUM_CREATE_PTR" envDefault:"false"`
	DefaultTTL int    `env:"TECHNITIUM_DEFAULT_TTL" envDefault:"300"`
	UseTTL     bool   `env:"TECHNITIUM_USE_TTL" envDefault:"true"`
	FQDNRegEx  string
	NameRegEx  string
}

// NewTechnitiumProviderWithToken creates a provider using the static token
func NewTechnitiumProviderWithToken(config *StartupConfig, domainFilter *endpoint.DomainFilter) (*Provider, error) {
	client := NewClientWithToken(
		config.Host,
		config.Port,
		config.Token,
		config.SSLVerify,
	)
	return &Provider{
		client:       client,
		domainFilter: domainFilter,
		config:       config,
	}, nil
}

// NewTechnitiumProviderWithCredentials creates a provider using managed sessions
func NewTechnitiumProviderWithCredentials(config *StartupConfig, domainFilter *endpoint.DomainFilter) (*Provider, error) {
	client := NewClientWithCredentials(
		config.Host,
		config.Port,
		config.Username,
		config.Password,
		config.SSLVerify,
	)
	return &Provider{
		client:       client,
		domainFilter: domainFilter,
		config:       config,
	}, nil
}

// Records returns the list of all DNS records from the provider.
func (p *Provider) Records(ctx context.Context) ([]*endpoint.Endpoint, error) {
	var endpoints []*endpoint.Endpoint

	data, err := p.client.DoRequest(http.MethodGet, "/api/zones/list", nil)
	if err != nil {
		return nil, err
	}

	var zoneResp struct {
		Response struct {
			Zones []Zone `json:"zones"`
		} `json:"response"`
	}
	if err := json.Unmarshal(data, &zoneResp); err != nil {
		return nil, err
	}

	for _, zone := range zoneResp.Response.Zones {
		if !p.domainFilter.Match(zone.Name) {
			continue
		}

		params := url.Values{}
		params.Set("domain", zone.Name)
		params.Set("zone", zone.Name)
		params.Set("listZone", "true")

		recData, err := p.client.DoRequest(http.MethodGet, "/api/zones/records/get", params)
		if err != nil {
			return nil, err
		}

		var recResp struct {
			Response struct {
				Records []ZoneRecord `json:"records"`
			} `json:"response"`
		}
		err = json.Unmarshal(recData, &recResp)
		if err != nil {
			return nil, err
		}

		for _, r := range recResp.Response.Records {
			if provider.SupportedRecordType(r.Type) {
				endpoints = append(endpoints, endpoint.NewEndpointWithTTL(
					r.Name,
					r.Type,
					endpoint.TTL(r.TTL),
					r.GetDataValue(),
				))
			}
		}
	}
	log.Debugf("fetched %d records from technitium", len(endpoints))
	return endpoints, nil
}

// ApplyChanges applies the given set of changes (Create, Update, Delete) to the DNS provider.
func (p *Provider) ApplyChanges(_ context.Context, changes *plan.Changes) error {

	for _, ep := range changes.Create {
		if err := p.updateRecord("add", ep); err != nil {
			return err
		}
	}

	for _, ep := range changes.UpdateOld {
		if err := p.updateRecord("delete", ep); err != nil {
			return err
		}
	}

	for _, ep := range changes.UpdateNew {
		if err := p.updateRecord("add", ep); err != nil {
			return err
		}
	}

	for _, ep := range changes.Delete {
		if err := p.updateRecord("delete", ep); err != nil {
			return err
		}
	}

	return nil
}

// updateRecord Updates the record to the DNS server.
func (p *Provider) updateRecord(action string, ep *endpoint.Endpoint) error {

	// Technitium API paths
	path := "/api/zones/records/add"
	if action == "delete" {
		path = "/api/zones/records/delete"
	}

	for _, target := range ep.Targets {
		params := url.Values{}
		params.Set("domain", ep.DNSName)
		params.Set("type", ep.RecordType)

		switch ep.RecordType {
		case RecordTypeA, RecordTypeAAAA:
			params.Set("ipAddress", target)
		case RecordTypeCNAME:
			params.Set("cname", target)
		case RecordTypeTXT:
			params.Set("text", target)
		default:
			params.Set("value", target)
		}

		if action == "add" {
			params.Set("ttl", fmt.Sprintf("%d", ep.RecordTTL))
			params.Set("overwrite", "true")
			if p.config != nil && p.config.CreatePTR && (ep.RecordType == "A" || ep.RecordType == "AAAA") {
				params.Set("ptr", "true")
				params.Set("createPtrZone", "true")
			}
		}

		_, err := p.client.DoRequest(http.MethodGet, path, params)
		if err != nil {
			log.Errorf("Failed to %s record %s: %v", action, ep.DNSName, err)
			return err
		}
	}
	return nil
}

// AdjustEndpoints allows the provider to normalize endpoints (like TTLs) before they are processed.
func (p *Provider) AdjustEndpoints(endpoints []*endpoint.Endpoint) ([]*endpoint.Endpoint, error) {
	for _, ep := range endpoints {
		if !ep.RecordTTL.IsConfigured() {
			ep.RecordTTL = endpoint.TTL(p.config.DefaultTTL)
		}
	}
	return endpoints, nil
}

// GetDomainFilter returns the domain filter used by the provider.
func (p *Provider) GetDomainFilter() endpoint.DomainFilterInterface {
	return p.domainFilter
}
