package technitium

/*
Copyright 2024 The external-dns-technitium-webhook Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"

	"sigs.k8s.io/external-dns/endpoint"
	"sigs.k8s.io/external-dns/plan"
	"sigs.k8s.io/external-dns/provider"
)

type Provider struct {
	provider.BaseProvider
	client       *Client
	domainFilter *endpoint.DomainFilter
	config       *StartupConfig
}

// StartupConfig clarifies the method signature
type StartupConfig struct {
	Host       string `env:"TECHNITIUM_HOST,required" envDefault:"localhost"`
	Port       int    `env:"TECHNITIUM_PORT,required" envDefault:"53443"`
	Username   string `env:"TECHNITIUM_USER"`
	Password   string `env:"TECHNITIUM_PASSWORD"`
	Token      string `env:"TECHNITIUM_TOKEN"`
	SessionTTL int    `env:"TECHNITIUM_SESSION_TTL" envDefault:"30"`
	SSLVerify  bool   `env:"TECHNITIUM_SSL_VERIFY" envDefault:"false"`
	DryRun     bool   `env:"TECHNITIUM_DRY_RUN" envDefault:"false"`
	CreatePTR  bool   `env:"TECHNITIUM_CREATE_PTR" envDefault:"false"`
	DefaultTTL int    `env:"TECHNITIUM_DEFAULT_TTL" envDefault:"300"`
	UseTTL     bool   `env:"TECHNITIUM_USE_TTL" envDefault:"true"`
	FQDNRegEx  string
	NameRegEx  string
}

// NewTechnitiumProviderWithToken creates a provider using the static token
func NewTechnitiumProviderWithToken(config *StartupConfig, domainFilter *endpoint.DomainFilter) (*Provider, error) {
	client := NewClientWithToken(
		config.Host,
		config.Token,
		config.SSLVerify,
	)
	return &Provider{client: client, domainFilter: domainFilter}, nil
}

// NewTechnitiumProviderWithCredentials creates a provider using managed sessions
func NewTechnitiumProviderWithCredentials(config *StartupConfig, domainFilter *endpoint.DomainFilter) (*Provider, error) {
	client := NewClientWithCredentials(
		config.Host,
		config.Username,
		config.Password,
		config.SSLVerify,
	)
	return &Provider{client: client, domainFilter: domainFilter}, nil
}

// Records returns the list of all DNS records from the provider.
func (p *Provider) Records(ctx context.Context) ([]*endpoint.Endpoint, error) {
	// 1. Use p.client to fetch zones/records from Technitium
	// 2. Filter them using p.domainFilter.Match(domain)
	// 3. Convert them to []*endpoint.Endpoint
	return nil, nil
}

// ApplyChanges applies the given set of changes (Create, Update, Delete) to the DNS provider.
func (p *Provider) ApplyChanges(ctx context.Context, changes *plan.Changes) error {
	// 1. Iterate through changes.Create, changes.UpdateOld/UpdateNew, and changes.Delete
	// 2. Use p.client to make the corresponding API calls to Technitium
	return nil
}

// AdjustEndpoints allows the provider to normalize endpoints (like TTLs) before they are processed.
func (p *Provider) AdjustEndpoints(endpoints []*endpoint.Endpoint) ([]*endpoint.Endpoint, error) {
	for _, ep := range endpoints {
		if !ep.RecordTTL.IsConfigured() {
			ep.RecordTTL = endpoint.TTL(p.config.DefaultTTL)
		}
	}
	return endpoints, nil
}

// GetDomainFilter returns the domain filter used by the provider.
func (p *Provider) GetDomainFilter() endpoint.DomainFilterInterface {
	return p.domainFilter
}
