package technitium

/*
Copyright 2024 The external-dns-technitium-webhook Contributors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

type Zone struct {
	Name string `json:"name"`
}

type ZoneRecord struct {
	Name string `json:"name"`
	Type string `json:"type"`
	TTL  int    `json:"ttl"`
	Data struct {
		Address string `json:"address,omitempty"` // A, AAAA
		CNAME   string `json:"cname,omitempty"`   // CNAME
		Text    string `json:"text,omitempty"`    // TXT
		Value   string `json:"value,omitempty"`   // Generic
	} `json:"data"`
}

// GetDataValue Helper to extract string value from Technitium's polymorphic data object
func (r ZoneRecord) GetDataValue() string {
	if r.Data.Address != "" {
		return r.Data.Address
	}
	if r.Data.CNAME != "" {
		return r.Data.CNAME
	}
	if r.Data.Text != "" {
		return r.Data.Text
	}
	return r.Data.Value
}
